### ISSUE TITLE
Retaining metadata on remove silence

### ISSUE THREAD

**Issue by faxinadu** [SamWindell/AudioUtils#7]
I wonder about this caveat:

"However, in the case that Signet chops away part of the audio that contained a marker or loop, a warning will be issued as there is no reasonable way to resolve this."

The most common case I would think is removal of silence at the sample start. In that case, can not the loop points just be adjusted by subtracting from the loop start and end the number of samples removed?

**Comment by SamWindell** [comment]
If there are no markers in the silent bit that is trimmed away, but there are markers later in the file, the remaining marker will be adjusted so that they still line up with the data before the trim. 

If there are markers in the bit that is trimmed away I'm still not sure what we can do? Is that what you mean here?
